name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - release-*
      - 1.1.x
    tags-ignore: [ v.* ]

env:
  AKKA_TEST_TIMEFACTOR: 10.0
  EVENT_NAME: ${{ github.event_name }}

jobs:
  check-code-compilation:
    name: Check Code Compilation
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Compile all code with default compiler
        run: sbt "Test/compile"

  test:
    name: Build and Test
    runs-on: ubuntu-20.04
    needs: [check-code-compilation]
    strategy:
      fail-fast: false
      matrix:
        include:
          - { java-version: 8,  scala-version: 2.12.15, sbt-opts: '' }
          - { java-version: 8,  scala-version: 2.13.7, sbt-opts: '' }
          - { java-version: 11, scala-version: 2.12.15,  sbt-opts: '-J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler' }
          - { java-version: 11, scala-version: 2.13.7, sbt-opts: '-J-XX:+UnlockExperimentalVMOptions -J-XX:+UseJVMCICompiler' }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Run tests with Scala ${{ matrix.scala-version }} and Java ${{ matrix.java-version }}
        run: sbt "++${{ matrix.scala-version }} test" ${{ matrix.sbt-opts }}

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
